### ISSUE TITLE
请问什么时候会上传2017年的视频呢？

### ISSUE THREAD

**Issue by q61946532** [atConf/atswift-2017-resources#1]
请问什么时候会上传2017年的视频呢？

**Comment by dianqk** [comment]
Hi @q61946532 ,

视频是由 StuQ 承办的，目前已经制作完成（无字幕）。

链接见 http://www.stuq.org/course/1190 。

如果您参加过 2017 @Swift 可以免费观看，方式请回想大会结束时提供的观看方法。
